name: Create Experience for Big PR

on:
  pull_request:
    types:
      - closed

env:
  SIMPLE_EXP_SUMMARY: 'A tad too big PR experience...'

jobs:
  create-experience-pr-too-big:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Create Experience for Big PR
        uses: neelix-io/practices-experience-action@v1.0.0
        with:
          api-token: ${{ secrets.NEELIX_API_TOKEN }}
          consortium-id: ${{ vars.CONSORTIUM_ID }}
          commentary: "A tad too big PR experience"
          weight: -1
          activity-id: 49
          category-ids: 30107
          team-ids: 7164
          code-changed-limit: 20,
