name: Create Experience for Too Long Running PR

on:
  pull_request:
    types:
      - closed

env:
  SIMPLE_EXP_SUMMARY: 'A tad too long running PR experience...'

jobs:
  create-experience-long-running-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Create Experience for too long running PR
        uses: neelix-io/practices-experience-action@v1.0.0
        with:
          api-token: ${{ secrets.NEELIX_API_TOKEN }}
          consortium-id: ${{ vars.CONSORTIUM_ID }}
          commentary: "A tad too long running PR experience"
          weight: -1
          activity-id: 49
          category-ids: 30107
          team-ids: 7164
          days-to-merge-limit: 5,
