name: Create Experience Related to Tech Debt

on:
  pull_request:
    types:
      - closed

env:
  SIMPLE_EXP_SUMMARY: 'Reflection on Tech Debt ...'

jobs:
  create-experience-smth-is-fishy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Create Experience - Reflection on Tech Debt
        uses: neelix-io/simple-net-experience-action@v1
        with:
          api-token: ${{ secrets.NEELIX_API_TOKEN }}
          consortium-id: ${{ vars.CONSORTIUM_ID }}
          experience-summary: ${{ env.SIMPLE_EXP_SUMMARY }}
          keywords: |
            {
              "regrettable tech debt": -1,
              "paying back tech debt": 1
            }
          activity-id: 49
          category-ids: 100,30108,95
          team-ids: 7164