name: Create Experience Something is Fishy

on:
  pull_request:
    types:
      - closed

env:
  SIMPLE_EXP_SUMMARY: 'Something is fishy about this PR...'

jobs:
  create-experience-smth-is-fishy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create Experience - Something is fishy
        uses: neelix-io/simple-net-experience-action@v1.0.0
        with:
          api-token: ${{ secrets.NEELIX_API_TOKEN }}
          consortium-id: ${{ vars.CONSORTIUM_ID }}
          experience-summary: ${{ env.SIMPLE_EXP_SUMMARY }}
          keywords: |
            {
              "not quite correct": -1,
              "needs improvement": -1,
              "will suffer": -2,
              "fishy": -1,
              "smashed it": 2
            }
          activity-id: 49
          category-ids: 96,30108
          team-ids: 7164